baseURL = "https://brave-yalow-9c02d4.netlify.app/"
languageCode = "en-us"
title = "My New Hugo Site"

[module]

[[module.imports]]
  path = "github.com/pointyfar/hmd-content"
  disable=false
  [[module.imports.mounts]]
    source="content/looking-glass"
    target="content/looking-glass"
  [[module.imports.mounts]]
    source="animals"
    target="content/animals"
    

[[module.mounts]]
    source = "hmd-private"
    target = "content/private"
    

[[module.imports]]
  path = "github.com/pointyfar/hmd-theme"
  disable = false

[[module.imports]]
  path = "github.com/jgthms/bulma"
  disable = false
  [[module.imports.mounts]]
    source = "."
    target = "assets/bulma"
